[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "python3 -m uvicorn src.main:app --reload"
healthcheckPath = "api/docs"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"