[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "uvicorn src.main:app --host 0.0.0.0 --port 8000"
healthcheckPath = "/api/docs"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"